updated

diff --git a/.github/workflows/appCI.yml b/.github/workflows/appCI.yml
--- a/.github/workflows/appCI.yml
+++ b/.github/workflows/appCI.yml
@@ -59,22 +59,16 @@ jobs:
     needs: Backup-the-exisiting-app
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      
-      - name: Install dependencies
-        run: npm install
-
-      - name: build app
-        run: npm run build
-
-      - name: Verify build folder
-        run: ls -l
-
-      - name: Archive dist folder
+      - name: Archive whole project
         run: |
-          tar -czf dist.tar.gz dist
-          ls -lh dist.tar.gz  
+          PROJECT_NAME="sms-$(date +'%Y-%m-%d-%H%M%S')"
+          if [ -d "." ]; then
+            tar -czf ${PROJECT_NAME}.tar.gz .
+            ls -lh ${PROJECT_NAME}.tar.gz
+          else
+            echo "Error: project folder does not exist!"
+            exit 1
+          fi
 
       - name: Copy files to the server
         uses: appleboy/scp-action@v0.1.7
@@ -82,7 +76,7 @@ jobs:
           host: ${{ secrets.WEB_HOST }}
           username: ${{ secrets.WEB_USER }}
           key: ${{ secrets.TEST_SSHKEY }}
-          source: dist.tar.gz
+          source: "${PROJECT_NAME}.tar.gz"
           target: "/home/ec2-user/downloads/"
           strip_components: 0 
           
@@ -93,8 +87,11 @@ jobs:
           username: ${{ secrets.WEB_USER }}
           key: ${{ secrets.TEST_SSHKEY }}
           script: |
-            sudo tar -xzf /home/ec2-user/downloads/dist.tar.gz
-            sudo cp -r /home/ec2-user/downloads/dist* /usr/share/nginx/html/
+            sudo tar -xzf /home/ec2-user/downloads/${PROJECT_NAME}.tar.gz
+            sudo cp /home/ec2-user/downloads/${PROJECT_NAME} /home/ec2-user/apps/
+            npm install
+            npm run build
+            sudo cp -r /home/ec2-user/apps/dist* /usr/share/nginx/html/
             sudo systemctl restart nginx
 
   Execute-Selenium-Tests:
